/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package algGui;

import algBo.Networking;
import algController.ClientController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author salim
 */
public class AlgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlgJPanel
     */
    private static ClientController sipClientController;

    public static ClientController getSipClientController() {
        return sipClientController;
    }

    public static void setSipClientController(ClientController sipClientController) {
        AlgJFrame.sipClientController = sipClientController;
    }
    public AlgJPanel(ClientController sipClientController) {
        initComponents();
        AlgJPanel.sipClientController = sipClientController;
    }
    
      public AlgJPanel() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultmsg = new javax.swing.JLabel();
        comb1DestPort = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        runALGtest = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comb1SrcPort = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comb1Proto = new javax.swing.JLabel();
        jTabbedPane1Reg = new javax.swing.JTabbedPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        comb1SentMsgREG = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        comb1SentMsgINV = new javax.swing.JTextArea();
        jTabbedPane2Reg = new javax.swing.JTabbedPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        comb1RcvMsgREG = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        comb1RcvMsgINV = new javax.swing.JTextArea();
        comb1Proto1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comb1DestPort1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        comb1SrcPort1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        comb1SentMsg1 = new javax.swing.JTextArea();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        comb1RcvMsg1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        comb1SentMsg2 = new javax.swing.JTextArea();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        comb1RcvMsg2 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        comb1SentMsg3 = new javax.swing.JTextArea();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        comb1RcvMsg3 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        comb1Proto2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        comb1DestPort2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        comb1SrcPort2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        comb1Proto3 = new javax.swing.JLabel();
        comb1SrcPort3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        comb1DestPort3 = new javax.swing.JLabel();

        resultmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultmsg.setText("Result message");
        resultmsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 27, 27)));

        comb1DestPort.setText("5060");

        jLabel6.setText("Transport:");

        runALGtest.setText("Run Test");
        runALGtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runALGtestActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(230, 137, 45));
        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel26.setText("ALG Detector");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel2.setText("Source Port:");

        comb1SrcPort.setText("5062");

        jLabel4.setText("Destination Port:");

        comb1Proto.setText("UDP");
        comb1Proto.setOpaque(true);

        jTabbedPane1Reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1RegMousePressed(evt);
            }
        });

        comb1SentMsgREG.setColumns(20);
        comb1SentMsgREG.setRows(5);
        comb1SentMsgREG.setText("Sent message:");
        jScrollPane9.setViewportView(comb1SentMsgREG);

        jTabbedPane1Reg.addTab("Register", jScrollPane9);

        comb1SentMsgINV.setColumns(20);
        comb1SentMsgINV.setRows(5);
        comb1SentMsgINV.setText("Sent message:");
        jScrollPane1.setViewportView(comb1SentMsgINV);

        jTabbedPane1Reg.addTab("Invite", jScrollPane1);

        comb1RcvMsgREG.setColumns(20);
        comb1RcvMsgREG.setRows(5);
        comb1RcvMsgREG.setText("Received message:");
        jScrollPane10.setViewportView(comb1RcvMsgREG);

        jTabbedPane2Reg.addTab("Register", jScrollPane10);

        comb1RcvMsgINV.setColumns(20);
        comb1RcvMsgINV.setRows(5);
        comb1RcvMsgINV.setText("Received message:");
        jScrollPane2.setViewportView(comb1RcvMsgINV);

        jTabbedPane2Reg.addTab("Invite", jScrollPane2);

        comb1Proto1.setText("TCP");
        comb1Proto1.setOpaque(true);

        jLabel3.setText("Source Port:");

        comb1DestPort1.setText("5060");

        jLabel25.setText("Transport:");

        comb1SrcPort1.setText("5062");

        jLabel5.setText("Destination Port:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane11.setViewportView(jTextArea3);

        jTabbedPane3.addTab("tab2", jScrollPane11);

        comb1SentMsg1.setColumns(20);
        comb1SentMsg1.setRows(5);
        comb1SentMsg1.setText("Sent message:");
        jScrollPane3.setViewportView(comb1SentMsg1);

        jTabbedPane3.addTab("tab1", jScrollPane3);

        comb1RcvMsg1.setColumns(20);
        comb1RcvMsg1.setRows(5);
        comb1RcvMsg1.setText("Received message:");
        jScrollPane4.setViewportView(comb1RcvMsg1);

        jTabbedPane4.addTab("tab2", jScrollPane4);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane12.setViewportView(jTextArea4);

        jTabbedPane4.addTab("tab2", jScrollPane12);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane13.setViewportView(jTextArea9);

        jTabbedPane5.addTab("tab2", jScrollPane13);

        comb1SentMsg2.setColumns(20);
        comb1SentMsg2.setRows(5);
        comb1SentMsg2.setText("Sent message:");
        jScrollPane14.setViewportView(comb1SentMsg2);

        jTabbedPane5.addTab("tab1", jScrollPane14);

        comb1RcvMsg2.setColumns(20);
        comb1RcvMsg2.setRows(5);
        comb1RcvMsg2.setText("Received message:");
        jScrollPane15.setViewportView(comb1RcvMsg2);

        jTabbedPane6.addTab("tab2", jScrollPane15);

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane16.setViewportView(jTextArea10);

        jTabbedPane6.addTab("tab2", jScrollPane16);

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jScrollPane17.setViewportView(jTextArea11);

        jTabbedPane7.addTab("tab2", jScrollPane17);

        comb1SentMsg3.setColumns(20);
        comb1SentMsg3.setRows(5);
        comb1SentMsg3.setText("Sent message:");
        jScrollPane18.setViewportView(comb1SentMsg3);

        jTabbedPane7.addTab("tab1", jScrollPane18);

        comb1RcvMsg3.setColumns(20);
        comb1RcvMsg3.setRows(5);
        comb1RcvMsg3.setText("Received message:");
        jScrollPane19.setViewportView(comb1RcvMsg3);

        jTabbedPane8.addTab("tab2", jScrollPane19);

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jScrollPane20.setViewportView(jTextArea12);

        jTabbedPane8.addTab("tab2", jScrollPane20);

        comb1Proto2.setText("UDP");
        comb1Proto2.setOpaque(true);

        jLabel27.setText("Source Port:");

        jLabel28.setText("Destination Port:");

        comb1DestPort2.setText("5060");

        jLabel29.setText("Transport:");

        comb1SrcPort2.setText("5060");

        jLabel30.setText("Source Port:");

        jLabel31.setText("Destination Port:");

        comb1Proto3.setText("TCP");
        comb1Proto3.setOpaque(true);

        comb1SrcPort3.setText("5060");

        jLabel32.setText("Transport:");

        comb1DestPort3.setText("5060");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1Proto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1SrcPort1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addComponent(comb1DestPort1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1Proto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1SrcPort2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addGap(9, 9, 9)
                                .addComponent(comb1DestPort2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1Proto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb1SrcPort3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addGap(9, 9, 9)
                                .addComponent(comb1DestPort3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(jTabbedPane2Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(100, 100, 100))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(runALGtest)
                                        .addGap(93, 93, 93)
                                        .addComponent(reset)
                                        .addGap(45, 45, 45))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTabbedPane1Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comb1Proto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comb1SrcPort)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addGap(9, 9, 9)
                                .addComponent(comb1DestPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(resultmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(runALGtest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comb1Proto)
                            .addComponent(jLabel2)
                            .addComponent(comb1SrcPort)
                            .addComponent(jLabel4)
                            .addComponent(comb1DestPort)))
                    .addComponent(resultmsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(comb1Proto1)
                    .addComponent(jLabel3)
                    .addComponent(comb1SrcPort1)
                    .addComponent(jLabel5)
                    .addComponent(comb1DestPort1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(comb1Proto2)
                    .addComponent(jLabel27)
                    .addComponent(comb1SrcPort2)
                    .addComponent(jLabel28)
                    .addComponent(comb1DestPort2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(comb1Proto3)
                    .addComponent(jLabel30)
                    .addComponent(comb1SrcPort3)
                    .addComponent(jLabel31)
                    .addComponent(comb1DestPort3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runALGtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runALGtestActionPerformed

        if (getSipClientController() == null) {
            try {
                sipClientController = new ClientController();
                sipClientController.createSipStack();
                sipClientController.createSipFrameWork();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                try {
                    sipClientController.reset();
                } catch (Exception ex1) {
                  JOptionPane.showMessageDialog(this, ex1.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                sipClientController = null;
            }
        }
        //Send register then invite
            String resReg = sipClientController.sendRegisterStateless();
            String resInv = sipClientController.sendInvite();
            //TODO: invoke the message comparision algo between the sent and received
            
            
            //filling the output log after sending the messeges
           //REG
            comb1SentMsgREG.setText(resReg);
            //set the caret to the top always
            comb1SentMsgREG.setCaretPosition(0);
            
            //INV
            comb1SentMsgINV.setText(resInv);
            //set the caret to the top always
            comb1SentMsgINV.setCaretPosition(0);
       
    }//GEN-LAST:event_runALGtestActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
//        System.out.println("resetActionPerformed begin..");
//          String msg = "";
//          if(sipClientController != null){
//              System.out.println("resetActionPerformed sipClientController is not null");
//              try{
//          msg = sipClientController.reset();
//          sipClientController = null;
//        }
//        catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);    
//            }
//        resultmsg.setText(msg);
        
        //clean the text areas:
        comb1SentMsgREG.setText("Sent message:");
        comb1SentMsgINV.setText("Sent message:");
        comb1RcvMsgREG.setText("Received message:");
        comb1RcvMsgINV.setText("Received message:");  
        resultmsg.setText("OK");
    }//GEN-LAST:event_resetActionPerformed

    private void jTabbedPane1RegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1RegMousePressed

        //TODO: once the user click on register -> click on the register received tab
    }//GEN-LAST:event_jTabbedPane1RegMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel comb1DestPort;
    public javax.swing.JLabel comb1DestPort1;
    public javax.swing.JLabel comb1DestPort2;
    public javax.swing.JLabel comb1DestPort3;
    public javax.swing.JLabel comb1Proto;
    public javax.swing.JLabel comb1Proto1;
    public javax.swing.JLabel comb1Proto2;
    public javax.swing.JLabel comb1Proto3;
    public static javax.swing.JTextArea comb1RcvMsg1;
    public static javax.swing.JTextArea comb1RcvMsg2;
    public static javax.swing.JTextArea comb1RcvMsg3;
    public static javax.swing.JTextArea comb1RcvMsgINV;
    public static javax.swing.JTextArea comb1RcvMsgREG;
    private static javax.swing.JTextArea comb1SentMsg1;
    private static javax.swing.JTextArea comb1SentMsg2;
    private static javax.swing.JTextArea comb1SentMsg3;
    private static javax.swing.JTextArea comb1SentMsgINV;
    private javax.swing.JTextArea comb1SentMsgREG;
    public javax.swing.JLabel comb1SrcPort;
    public javax.swing.JLabel comb1SrcPort1;
    public javax.swing.JLabel comb1SrcPort2;
    public javax.swing.JLabel comb1SrcPort3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1Reg;
    private javax.swing.JTabbedPane jTabbedPane2Reg;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JButton reset;
    public static javax.swing.JLabel resultmsg;
    private javax.swing.JButton runALGtest;
    // End of variables declaration//GEN-END:variables
}
